spring.application.name=bai4
server.port=8081

# Database configuration
# If you are running this application in a Docker container and your database is on the host machine,
# you might need to change '127.0.0.1' to 'host.docker.internal'.
# Please also ensure that the username and password are correct for your database.
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bai5
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
